"""Fixed-vector representation artifact contracts."""

from supervised_learning_polymers.representations.contracts import (
    FeatureFamily,
    FeatureMatrixBundle,
    FeatureMatrixMetadata,
    FeatureNamePolicy,
    FeatureSetConfig,
    FeatureSetDimension,
    MolecularInputRepresentation,
    RepresentationArtifact,
    RepresentationArtifactPaths,
    RepresentationAttemptRecord,
    RepresentationAttemptStatus,
    RepresentationConfig,
    RepresentationFailureGroup,
    RepresentationFailureRecord,
    RepresentationFailureType,
    RepresentationOutputMetadata,
    RepresentationProcessingStage,
    RepresentationSummary,
    feature_matrix_hash,
    feature_names_hash,
    generate_rdkit_2d_features,
    rdkit_2d_feature_set_config,
    representation_artifact_dir,
    representation_cache_key,
)

__all__ = [
    "FeatureFamily",
    "FeatureMatrixBundle",
    "FeatureMatrixMetadata",
    "FeatureNamePolicy",
    "FeatureSetConfig",
    "FeatureSetDimension",
    "MolecularInputRepresentation",
    "RepresentationArtifact",
    "RepresentationArtifactPaths",
    "RepresentationConfig",
    "RepresentationFailureGroup",
    "RepresentationFailureRecord",
    "RepresentationFailureType",
    "RepresentationOutputMetadata",
    "RepresentationProcessingStage",
    "RepresentationSummary",
    "RepresentationAttemptRecord",
    "RepresentationAttemptStatus",
    "feature_matrix_hash",
    "feature_names_hash",
    "generate_rdkit_2d_features",
    "rdkit_2d_feature_set_config",
    "representation_artifact_dir",
    "representation_cache_key",
]
